safe: true
server_port: 4000
baseurl: /
source: .
destination: ./_site
plugins: ./_plugins
future: true
markdown: rdiscount
permalink: pretty
pygments: true
lsi: false
exclude: ["tumblr.rb", "assets", "Rakefile", "README.md", "CONTRIBUTING.md"]

rdiscount:
  extensions: [smart]

name: "Beer && Code Omaha"
url: http://omaha.beerandcode.org
github: BeerAndCode
twitter: BeerCodeOmaha
